### ISSUE TITLE
Mobile devices inssue

### ISSUE THREAD

**Issue by davidgm1987** [avokicchi/jquery-drawr#15]
Hello!
First of all, congratulations @lieuweprins  for the pluguin, it is awesome and help me a lot.
I used it in a web aplication that I need it can be used by mobile devices. The problem is that seems the plugin is blocking the links and the button of the page... It is rare, you can see it by watching your own web demo (https://rawrfl.es/jquery-drawr/ ) in a mobile device or by toogle device toolbar inside de F12 mode of Chrome. Click in "Download" or "View on github" or the links in the page and you will see it.
Do you know why is this happening?

Thanks you in advance!

![inssue drawr](https://user-images.githubusercontent.com/54616732/63832608-743aaa80-c971-11e9-8d20-0023ad5424c1.PNG)

**Comment by lieuweprins** [comment]
Hi, thanks for reporting.

It appears to be caused by the "e.preventDefault();" , line 185 of jquery.drawr.js, inside the self.drawStop method. commenting it out seems to fix things. I'm not sure why it is there to be honest (I imagine it had something to do with the text input control).

I'm looking into it, there don't seem to be any sideeffects as of yet for removing it but I need to be sure.

**Comment by mohammadwakeel** [comment]
Hi @lieuweprins  !
I'm want to use this plugin as whiteboard in my online Tutor website but i'm facing a issue on responsive, you can view this in image. please help me on this issue. Thanks in Advanced.
![Capture](https://user-images.githubusercontent.com/48790618/71461734-b1556300-27d2-11ea-8dfa-2cf884a5ea2b.PNG)
